version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node-app:
    build: .
    image: node-app:1.0
    ports:
        - '9999:9999'

